# Generated by Django 5.2.12 on 2026-03-14 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_display', models.CharField(max_length=50)),
                ('symptoms', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('moderate', 'Moderate'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asha_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_referrals', to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
