# Generated by Django 6.0.3 on 2026-03-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_initial'),
        ('doctors', '0004_doctor_bio_doctor_is_available_doctor_qualification'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='scheduled_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='consultation',
            name='call_type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='VIDEO', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
        ),
    ]
