# Generated by Django 6.0.3 on 2026-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_scheduled_at_consultation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
