# Generated by Django 6.0.3 on 2026-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0006_alter_consultation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("FOLLOW_UP", "Follow-up"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
