# Generated by Django 6.0.3 on 2026-03-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0007_alter_consultation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
    ]
