# Generated by Django 6.0.3 on 2026-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0008_consultation_is_emergency"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
