# Generated by Django 6.0.3 on 2026-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
