# Generated by Django 6.0.3 on 2026-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
