# Generated by Django 6.0.3 on 2026-03-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_bio_doctor_is_available_doctor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default='General Hospital', max_length=200),
            preserve_default=False,
        ),
    ]
