# Generated by Django 6.0.3 on 2026-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_doctor_license_number_alter_doctor_hospital_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="clinic_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consultation_mode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="working_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
