# Generated by Django 6.0.3 on 2026-03-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_doctor_clinic_location_doctor_consultation_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_profiles/"
            ),
        ),
    ]
