# Generated by Django 6.0.3 on 2026-08-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_rejection_reason_doctor_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_veterinarian',
            field=models.BooleanField(default=False, help_text='True when this clinician provides veterinary / livestock care advice.'),
        ),
    ]
