# Generated by Django 6.0.3 on 2026-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworker',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='worker_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
