# Generated by Django 6.0.3 on 2026-08-29 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('species', models.CharField(choices=[('CATTLE', 'Cattle'), ('BUFFALO', 'Buffalo'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('POULTRY', 'Poultry'), ('OTHER', 'Other')], default='CATTLE', max_length=20)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('HUMAN', 'Human'), ('ANIMAL', 'Animal')], default='HUMAN', max_length=10)),
                ('input_type', models.CharField(default='symptoms', max_length=20)),
                ('input_text', models.TextField(blank=True)),
                ('possible_condition', models.CharField(blank=True, max_length=160)),
                ('severity_level', models.CharField(default='Low', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('advice', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='one_health.livestockcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
