<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-21 17:47
=======
# Generated by Django 6.0.3 on 2026-03-21 12:44
>>>>>>> fee035fdefda48dc95a9fb53f469dc6dcaed41aa

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('patients', '0003_patient_abha_id_alter_patient_address_and_more'),
=======
        ('patients', '0002_initial'),
>>>>>>> fee035fdefda48dc95a9fb53f469dc6dcaed41aa
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(upload_to='health_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(default='Lab Report', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
=======
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('moderate', 'Moderate'), ('highRisk', 'High Risk')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='patients.patient')),
>>>>>>> fee035fdefda48dc95a9fb53f469dc6dcaed41aa
            ],
        ),
    ]
