# Generated by Django 6.0.3 on 2026-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
