# Generated by Django 6.0.3 on 2026-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_abha_id_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
