# Generated by Django 6.0.3 on 2026-03-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_emergencycontact_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='abha_id',
        ),
    ]
