# Generated by Django 6.0.3 on 2026-03-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_end_time'),
        ('doctors', '0005_doctor_license_number_alter_doctor_hospital_name'),
        ('patients', '0002_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
