# Generated by Django 6.0.3 on 2026-03-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0005_alter_consultation_status"),
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="dosage_instructions",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medications",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="consultation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="consultations.consultation",
            ),
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("instructions", models.TextField(blank=True)),
                ("timing", models.CharField(blank=True, max_length=100)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
