# Generated by Django 6.0.3 on 2026-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_doctor_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prescription_documents/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='file_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='prescription',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('handwritten', 'Handwritten')], db_index=True, default='digital', max_length=32),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
