# Generated by Django 6.0.3 on 2026-03-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_doctor_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
