# Generated by Django 6.0.3 on 2026-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_remove_prescription_dosage_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="purpose",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medication",
            name="route",
            field=models.CharField(default="Oral", max_length=100),
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
