# Generated by Django 6.0.3 on 2026-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0003_medication_purpose_medication_route_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="symptoms",
            field=models.TextField(blank=True),
        ),
    ]
