# Generated by Django 6.0.3 on 2026-03-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0004_prescription_symptoms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="symptoms",
        ),
    ]
