# Generated by Django 6.0.3 on 2026-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abha_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
