# Generated by Django 6.0.3 on 2026-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_otpverification_delete_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_switch_to_audio",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="consultation_duration_limit",
            field=models.CharField(default="15 minutes", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="consultation_requests_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="default_consultation_type",
            field=models.CharField(default="Video Call", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_alerts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="font_size",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="user",
            name="prescription_updates_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
