# Generated by Django 6.0.3 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('asha_worker', 'ASHA Worker'), ('medical_staff', 'Medical Staff')], default='user', max_length=20),
        ),
    ]
