# Generated by Django 6.0.3 on 2026-08-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_emergencyreferral'),
        ('doctors', '0005_doctor_license_number_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
